add volumes configration to attach tasks
rhythmictech/terraform-aws-nlb-ecs-task pull request #10
Opened 2022-04-15 03:24 UTC by vampire-yuta

Hi!  
I added volumes attached feature.
Please check it.

2022-04-18 14:00 UTC, sblack4 requested changes
Thank you! I think declaring a variable as a set will work but I haven't tested it.

2022-04-18 14:00 UTC, sblack4 commented on main.tf
> +    for_each = var.volumes
`for_each` only accepts maps or sets of strings https://www.terraform.io/language/meta-arguments/for_each#basic-syntax. `volumes` is list :(

2022-04-18 14:00 UTC, sblack4 commented on variables.tf
> +  type = list(object({
```suggestion
  type = set(object({
```

2022-07-22 01:40 UTC, vampire-yuta commented
Hi.  😸 
Your suggestion is fixed. How about it?? 👀

2022-07-27 17:44 UTC, sblack4 approved these changes

2022-07-27 17:44 UTC, merged